services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TrustMeBr0P@ssw0rd!"
    ports:
      - "1433:1433"
    volumes:
      - ./init:/init
    command: >
      /bin/sh -c "
        /opt/mssql/bin/sqlservr &
        sleep 20 &&
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$SA_PASSWORD\" -C -i /init/01-init.sql &&
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$SA_PASSWORD\" -C -i /init/02-init.sql &&
        wait
      "
  app:
    image: node:lts
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node index.js"
    depends_on:
      - db